name: checkout @v3 test

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: File list
        run: |
          pwd
          ls -a
      - name: Checkout @v3
        uses: actions/checkout@v3
      - name: File list after checkout
        run: |
          pwd
          ls -a
