name: checkout @v3 test

on:
  push:
  pull_request:
    types:
      - opened
      - closed
      - assigned

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: File list
        run: |
          ls -a
      - name: Checkout @v3
        uses: actions/checkout@v3
      - name: File list after checkout
        run: |
          ls -a
